/* The following code was generated by JFlex 1.4.3 on 24/02/12 18:45 */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 1998-2009  Gerwin Klein <lsf@jflex.de>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * This program is free software; you can redistribute it and/or modify    *
 * it under the terms of the GNU General Public License. See the file      *
 * COPYRIGHT for more information.                                         *
 *                                                                         *
 * This program is distributed in the hope that it will be useful,         *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of          *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
 * GNU General Public License for more details.                            *
 *                                                                         *
 * You should have received a copy of the GNU General Public License along *
 * with this program; if not, write to the Free Software Foundation, Inc., *
 * 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA                 *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* Java 1.2 language lexer specification */

/* Use together with unicode.flex for Unicode preprocesssing */
/* and java12.cup for a Java 1.2 parser                      */

/* Note that this lexer specification is not tuned for speed.
   It is in fact quite slow on integer and floating point literals, 
   because the input is read twice and the methods used to parse
   the numbers are not very fast. 
   For a production quality application (e.g. a Java compiler) 
   this could be optimized */


import ;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 24/02/12 18:45 from the specification file
 * <tt>/Users/luca/Sviluppo/itaco/src/main/Scanner.flex</tt>
 */
public class Scanner implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\66"+
    "\1\24\1\0\1\6\1\75\1\71\1\25\1\53\1\54\1\5\1\73"+
    "\1\62\1\23\1\21\1\4\1\10\1\16\1\76\1\15\1\77\1\17"+
    "\1\102\1\100\1\101\1\11\1\52\1\61\1\65\1\63\1\64\1\70"+
    "\1\0\3\14\1\103\1\22\1\20\5\6\1\12\13\6\1\13\2\6"+
    "\1\57\1\26\1\60\1\74\1\6\1\0\1\33\1\27\1\42\1\45"+
    "\1\32\1\47\1\6\1\43\1\35\2\6\1\31\1\40\1\34\1\30"+
    "\1\41\1\6\1\37\1\44\1\36\1\46\1\50\1\6\1\13\2\6"+
    "\1\55\1\72\1\56\1\67\41\7\2\0\4\6\4\0\1\6\2\0"+
    "\1\7\7\0\1\6\4\0\1\6\5\0\27\6\1\0\21\6\1\51"+
    "\15\6\1\0\u013f\6\31\0\162\6\4\0\14\6\16\0\5\6\11\0"+
    "\1\6\21\0\130\7\5\0\23\7\12\0\1\6\13\0\1\6\1\0"+
    "\3\6\1\0\1\6\1\0\24\6\1\0\54\6\1\0\46\6\1\0"+
    "\5\6\4\0\202\6\1\0\4\7\3\0\105\6\1\0\46\6\2\0"+
    "\2\6\6\0\20\6\41\0\46\6\2\0\1\6\7\0\47\6\11\0"+
    "\21\7\1\0\27\7\1\0\3\7\1\0\1\7\1\0\2\7\1\0"+
    "\1\7\13\0\33\6\5\0\3\6\15\0\4\7\14\0\6\7\13\0"+
    "\32\6\5\0\13\6\16\7\7\0\12\7\4\0\2\6\1\7\143\6"+
    "\1\0\1\6\10\7\1\0\6\7\2\6\2\7\1\0\4\7\2\6"+
    "\12\7\3\6\2\0\1\6\17\0\1\7\1\6\1\7\36\6\33\7"+
    "\2\0\3\6\60\0\46\6\13\7\1\6\u014f\0\3\7\66\6\2\0"+
    "\1\7\1\6\20\7\2\0\1\6\4\7\3\0\12\6\2\7\2\0"+
    "\12\7\21\0\3\7\1\0\10\6\2\0\2\6\2\0\26\6\1\0"+
    "\7\6\1\0\1\6\3\0\4\6\2\0\1\7\1\6\7\7\2\0"+
    "\2\7\2\0\3\7\11\0\1\7\4\0\2\6\1\0\3\6\2\7"+
    "\2\0\12\7\4\6\15\0\3\7\1\0\6\6\4\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\2\6\1\0\2\6\2\0"+
    "\1\7\1\0\5\7\4\0\2\7\2\0\3\7\13\0\4\6\1\0"+
    "\1\6\7\0\14\7\3\6\14\0\3\7\1\0\11\6\1\0\3\6"+
    "\1\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7"+
    "\1\6\10\7\1\0\3\7\1\0\3\7\2\0\1\6\17\0\2\6"+
    "\2\7\2\0\12\7\1\0\1\6\17\0\3\7\1\0\10\6\2\0"+
    "\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0"+
    "\1\7\1\6\6\7\3\0\2\7\2\0\3\7\10\0\2\7\4\0"+
    "\2\6\1\0\3\6\4\0\12\7\1\0\1\6\20\0\1\7\1\6"+
    "\1\0\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6"+
    "\1\0\2\6\3\0\2\6\3\0\3\6\3\0\10\6\1\0\3\6"+
    "\4\0\5\7\3\0\3\7\1\0\4\7\11\0\1\7\17\0\11\7"+
    "\11\0\1\6\7\0\3\7\1\0\10\6\1\0\3\6\1\0\27\6"+
    "\1\0\12\6\1\0\5\6\4\0\7\7\1\0\3\7\1\0\4\7"+
    "\7\0\2\7\11\0\2\6\4\0\12\7\22\0\2\7\1\0\10\6"+
    "\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6\2\0\1\7"+
    "\1\6\7\7\1\0\3\7\1\0\4\7\7\0\2\7\7\0\1\6"+
    "\1\0\2\6\4\0\12\7\22\0\2\7\1\0\10\6\1\0\3\6"+
    "\1\0\27\6\1\0\20\6\4\0\6\7\2\0\3\7\1\0\4\7"+
    "\11\0\1\7\10\0\2\6\4\0\12\7\22\0\2\7\1\0\22\6"+
    "\3\0\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\7"+
    "\4\0\6\7\1\0\1\7\1\0\10\7\22\0\2\7\15\0\60\6"+
    "\1\7\2\6\7\7\4\0\10\6\10\7\1\0\12\7\47\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6"+
    "\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6"+
    "\1\0\4\6\1\7\2\6\6\7\1\0\2\7\1\6\2\0\5\6"+
    "\1\0\1\6\1\0\6\7\2\0\12\7\2\0\2\6\42\0\1\6"+
    "\27\0\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\10\6\1\0\42\6\6\0\24\7\1\0\2\7\4\6"+
    "\4\0\10\7\1\0\44\7\11\0\1\7\71\0\42\6\1\0\5\6"+
    "\1\0\2\6\1\0\7\7\3\0\4\7\6\0\12\7\6\0\6\6"+
    "\4\7\106\0\46\6\12\0\51\6\7\0\132\6\5\0\104\6\5\0"+
    "\122\6\6\0\7\6\1\0\77\6\1\0\1\6\1\0\4\6\2\0"+
    "\7\6\1\0\1\6\1\0\4\6\2\0\47\6\1\0\1\6\1\0"+
    "\4\6\2\0\37\6\1\0\1\6\1\0\4\6\2\0\7\6\1\0"+
    "\1\6\1\0\4\6\2\0\7\6\1\0\7\6\1\0\27\6\1\0"+
    "\37\6\1\0\1\6\1\0\4\6\2\0\7\6\1\0\47\6\1\0"+
    "\23\6\16\0\11\7\56\0\125\6\14\0\u026c\6\2\0\10\6\12\0"+
    "\32\6\5\0\113\6\3\0\3\6\17\0\15\6\1\0\4\6\3\7"+
    "\13\0\22\6\3\7\13\0\22\6\2\7\14\0\15\6\1\0\3\6"+
    "\1\0\2\7\14\0\64\6\40\7\3\0\1\6\3\0\2\6\1\7"+
    "\2\0\12\7\41\0\3\7\2\0\12\7\6\0\130\6\10\0\51\6"+
    "\1\7\126\0\35\6\3\0\14\7\4\0\14\7\12\0\12\7\36\6"+
    "\2\0\5\6\u038b\0\154\6\224\0\234\6\4\0\132\6\6\0\26\6"+
    "\2\0\6\6\2\0\46\6\2\0\6\6\2\0\10\6\1\0\1\6"+
    "\1\0\1\6\1\0\1\6\1\0\37\6\2\0\65\6\1\0\7\6"+
    "\1\0\1\6\3\0\3\6\1\0\7\6\3\0\4\6\2\0\6\6"+
    "\4\0\15\6\5\0\3\6\1\0\7\6\17\0\4\7\32\0\5\7"+
    "\20\0\2\6\23\0\1\6\13\0\4\7\6\0\6\7\1\0\1\6"+
    "\15\0\1\6\40\0\22\6\36\0\15\7\4\0\1\7\3\0\6\7"+
    "\27\0\1\6\4\0\1\6\2\0\12\6\1\0\1\6\3\0\5\6"+
    "\6\0\1\6\1\0\1\6\1\0\1\6\1\0\4\6\1\0\3\6"+
    "\1\0\7\6\3\0\3\6\5\0\5\6\26\0\44\6\u0e81\0\3\6"+
    "\31\0\11\6\6\7\1\0\5\6\2\0\5\6\4\0\126\6\2\0"+
    "\2\7\2\0\3\6\1\0\137\6\5\0\50\6\4\0\136\6\21\0"+
    "\30\6\70\0\20\6\u0200\0\u19b6\6\112\0\u51a6\6\132\0\u048d\6\u0773\0"+
    "\u2ba4\6\u215c\0\u012e\6\2\0\73\6\225\0\7\6\14\0\5\6\5\0"+
    "\1\6\1\7\12\6\1\0\15\6\1\0\5\6\1\0\1\6\1\0"+
    "\2\6\1\0\2\6\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0"+
    "\66\6\50\0\15\6\3\0\20\7\20\0\4\7\17\0\2\6\30\0"+
    "\3\6\31\0\1\6\6\0\5\6\1\0\207\6\2\0\1\7\4\0"+
    "\1\6\13\0\12\7\7\0\32\6\4\0\1\6\1\0\32\6\12\0"+
    "\132\6\3\0\6\6\2\0\6\6\2\0\6\6\2\0\3\6\3\0"+
    "\2\6\3\0\2\6\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\1\12\13\5\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\40\1\41\2\1\2\42\1\1\1\2\1\0"+
    "\1\43\1\44\1\45\1\46\1\47\1\0\3\45\1\50"+
    "\1\46\1\0\1\51\1\52\1\53\1\0\12\5\1\54"+
    "\1\5\1\55\4\5\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\67\1\70\1\71\1\72"+
    "\1\73\1\74\2\75\1\76\1\77\1\100\1\101\1\102"+
    "\1\103\1\104\1\105\1\106\12\74\1\0\1\107\2\110"+
    "\2\45\1\46\2\0\6\5\1\111\12\5\1\112\1\113"+
    "\1\114\1\75\1\0\1\115\1\0\1\116\1\117\1\120"+
    "\1\121\1\122\1\123\1\124\1\125\1\126\1\110\2\45"+
    "\1\0\2\5\1\127\6\5\1\130\5\5\1\131\1\132"+
    "\1\110\2\45\1\0\10\5\1\133\1\5\1\134\1\135"+
    "\1\5\1\110\2\45\1\0\2\5\1\136\6\5\1\137"+
    "\1\140\1\110\2\45\1\0\3\5\1\141\1\142\2\5"+
    "\1\143\1\110\2\45\1\0\1\144\4\5\1\110\2\45"+
    "\1\0\2\5\1\145\1\146\1\110\2\45\1\0\1\147"+
    "\1\150\1\0\2\45\1\151\1\0\2\45\1\0\2\45"+
    "\1\0\2\45\1\0\2\45\1\0\2\45\1\0\1\45"+
    "\1\46\1\0\5\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\210\0\314\0\u0110\0\314\0\u0154\0\u0198"+
    "\0\u01dc\0\u0220\0\u0264\0\u02a8\0\u02ec\0\314\0\314\0\u0330"+
    "\0\u0374\0\u03b8\0\u03fc\0\u0440\0\u0484\0\u04c8\0\u050c\0\u0550"+
    "\0\u0594\0\u05d8\0\314\0\314\0\314\0\314\0\314\0\314"+
    "\0\314\0\314\0\314\0\u061c\0\u0660\0\u06a4\0\u06e8\0\314"+
    "\0\314\0\u072c\0\u0770\0\u07b4\0\u07f8\0\u083c\0\u0880\0\u08c4"+
    "\0\314\0\314\0\u0908\0\u094c\0\u0990\0\314\0\u09d4\0\u0a18"+
    "\0\u0a5c\0\314\0\314\0\u0aa0\0\u0ae4\0\314\0\u0b28\0\u0b6c"+
    "\0\u0bb0\0\u0bf4\0\314\0\u0c38\0\u0c7c\0\314\0\314\0\314"+
    "\0\u0cc0\0\u0d04\0\u0d48\0\u0d8c\0\u0dd0\0\u0e14\0\u0e58\0\u0e9c"+
    "\0\u0ee0\0\u0f24\0\u0f68\0\u01dc\0\u0fac\0\u0ff0\0\u1034\0\u1078"+
    "\0\u10bc\0\u1100\0\314\0\314\0\u1144\0\314\0\u1188\0\314"+
    "\0\314\0\314\0\314\0\314\0\314\0\314\0\314\0\314"+
    "\0\314\0\u11cc\0\u1210\0\314\0\314\0\314\0\314\0\314"+
    "\0\314\0\314\0\314\0\314\0\u1254\0\u1298\0\u12dc\0\u1320"+
    "\0\u1364\0\u13a8\0\u13ec\0\u1430\0\u1474\0\u14b8\0\u14fc\0\314"+
    "\0\u1540\0\u1584\0\u15c8\0\u160c\0\u1650\0\u1694\0\u16d8\0\u171c"+
    "\0\u1760\0\u17a4\0\u17e8\0\u182c\0\u1870\0\u01dc\0\u18b4\0\u18f8"+
    "\0\u193c\0\u1980\0\u19c4\0\u1a08\0\u1a4c\0\u1a90\0\u1ad4\0\u1b18"+
    "\0\314\0\u1b5c\0\314\0\314\0\u1298\0\314\0\u1ba0\0\314"+
    "\0\314\0\314\0\314\0\314\0\314\0\314\0\314\0\314"+
    "\0\u1be4\0\u1c28\0\u1c6c\0\u1cb0\0\u1cf4\0\u1d38\0\u01dc\0\u1d7c"+
    "\0\u1dc0\0\u1e04\0\u1e48\0\u1e8c\0\u1ed0\0\u01dc\0\u1f14\0\u1f58"+
    "\0\u1f9c\0\u1fe0\0\u2024\0\u01dc\0\314\0\u2068\0\u20ac\0\u20f0"+
    "\0\u2134\0\u2178\0\u21bc\0\u2200\0\u2244\0\u2288\0\u22cc\0\u2310"+
    "\0\u2354\0\u01dc\0\u2398\0\u01dc\0\u01dc\0\u23dc\0\u2420\0\u2464"+
    "\0\u24a8\0\u24ec\0\u2530\0\u2574\0\u01dc\0\u25b8\0\u25fc\0\u2640"+
    "\0\u2684\0\u26c8\0\u270c\0\u01dc\0\u01dc\0\u2750\0\u2794\0\u27d8"+
    "\0\u281c\0\u2860\0\u28a4\0\u28e8\0\u01dc\0\u01dc\0\u292c\0\u2970"+
    "\0\u01dc\0\u29b4\0\u29f8\0\u2a3c\0\u2a80\0\u01dc\0\u2ac4\0\u2b08"+
    "\0\u2b4c\0\u2b90\0\u2bd4\0\u2c18\0\u2c5c\0\u2ca0\0\u2ce4\0\u2d28"+
    "\0\u01dc\0\u01dc\0\u2d6c\0\u2db0\0\u2df4\0\u2e38\0\u01dc\0\u01dc"+
    "\0\u2e7c\0\u2ec0\0\u2f04\0\314\0\u2f48\0\u2f8c\0\u2fd0\0\u3014"+
    "\0\u3058\0\u309c\0\u30e0\0\u3124\0\u3168\0\u31ac\0\u31f0\0\u3234"+
    "\0\u3278\0\u32bc\0\u3300\0\u3344\0\u3388\0\u3388\0\u33cc\0\u3410"+
    "\0\u3454\0\u3498\0\u34dc\0\u3520";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\4\1\12"+
    "\1\13\3\11\3\13\1\11\1\14\1\11\1\15\1\16"+
    "\1\17\1\4\1\20\3\11\1\21\1\22\1\23\1\11"+
    "\1\24\1\11\1\25\1\26\1\11\1\27\1\30\1\11"+
    "\1\31\1\32\1\11\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\5\13"+
    "\1\11\1\57\1\60\1\61\21\57\1\62\1\57\1\63"+
    "\55\57\1\64\1\65\1\66\22\64\1\4\1\67\55\64"+
    "\106\0\1\6\105\0\1\70\1\71\55\0\1\72\103\0"+
    "\1\73\26\0\13\11\1\0\1\11\4\0\23\11\24\0"+
    "\6\11\10\0\1\74\1\75\1\76\1\77\1\0\1\100"+
    "\1\101\1\102\1\103\1\104\1\105\6\0\1\76\1\105"+
    "\12\0\1\106\1\0\1\103\26\0\1\100\2\102\1\75"+
    "\1\102\1\106\10\0\2\13\1\76\2\0\3\13\1\103"+
    "\1\104\1\105\6\0\1\76\1\105\12\0\1\106\1\0"+
    "\1\103\26\0\5\13\1\106\10\0\2\104\3\0\3\104"+
    "\56\0\5\104\24\0\1\107\37\0\1\110\12\0\1\111"+
    "\13\0\13\11\1\0\1\11\4\0\1\11\1\112\21\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\2\11"+
    "\1\113\20\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\17\11\1\114\3\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\5\11\1\115\3\11\1\116\11\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\6\11"+
    "\1\117\14\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\3\11\1\120\1\121\3\11\1\122\12\11\24\0"+
    "\6\11\6\0\13\11\1\0\1\11\4\0\14\11\1\123"+
    "\6\11\24\0\6\11\6\0\13\11\1\0\1\11\4\0"+
    "\3\11\1\124\1\125\16\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\1\11\1\126\21\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\2\11\1\127\1\11"+
    "\1\130\1\11\1\131\14\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\3\11\1\132\17\11\24\0\6\11"+
    "\63\0\1\133\103\0\1\134\1\135\102\0\1\136\1\0"+
    "\1\137\101\0\1\140\103\0\1\141\5\0\1\142\75\0"+
    "\1\143\6\0\1\144\74\0\1\145\7\0\1\146\73\0"+
    "\1\147\103\0\1\150\20\0\1\57\2\0\21\57\1\0"+
    "\1\57\1\0\55\57\2\0\1\61\101\0\2\151\1\0"+
    "\5\151\1\152\4\151\2\152\1\153\4\151\1\154\1\155"+
    "\1\156\1\157\4\151\1\160\1\151\1\161\1\162\7\151"+
    "\1\163\26\151\1\152\2\153\1\151\1\153\1\151\25\0"+
    "\1\164\60\0\1\66\101\0\2\151\1\0\5\151\1\165"+
    "\4\151\2\165\1\166\4\151\1\167\1\170\1\171\1\172"+
    "\4\151\1\173\1\151\1\174\1\175\7\151\1\176\26\151"+
    "\1\165\2\166\1\151\1\166\1\151\1\70\1\5\1\6"+
    "\101\70\5\71\1\177\76\71\10\0\1\74\1\75\1\200"+
    "\2\0\1\100\1\101\1\102\1\103\1\104\1\105\6\0"+
    "\1\200\1\105\12\0\1\106\1\0\1\103\26\0\1\100"+
    "\2\102\1\75\1\102\1\106\10\0\2\75\3\0\3\75"+
    "\1\103\1\104\1\105\7\0\1\105\12\0\1\106\1\0"+
    "\1\103\26\0\5\75\1\106\10\0\1\201\1\202\2\0"+
    "\5\202\1\0\1\202\4\0\1\202\2\0\2\202\6\0"+
    "\1\202\2\0\1\202\1\0\1\202\26\0\6\202\10\0"+
    "\1\203\1\75\1\200\2\0\3\203\1\103\1\104\1\105"+
    "\6\0\1\200\1\105\12\0\1\106\1\0\1\103\26\0"+
    "\3\203\1\75\1\203\1\106\10\0\1\102\1\75\1\200"+
    "\2\0\3\102\1\103\1\104\1\105\6\0\1\200\1\105"+
    "\12\0\1\106\1\0\1\103\26\0\3\102\1\75\1\102"+
    "\1\106\10\0\1\204\1\75\1\200\2\0\3\204\1\103"+
    "\1\104\1\105\6\0\1\200\1\105\12\0\1\106\1\0"+
    "\1\103\26\0\3\204\1\75\1\204\1\106\10\0\2\104"+
    "\3\0\3\104\1\103\1\0\1\105\7\0\1\105\12\0"+
    "\1\106\1\0\1\103\26\0\5\104\1\106\10\0\2\205"+
    "\3\0\3\205\3\0\1\206\47\0\1\206\2\0\5\205"+
    "\17\0\1\207\73\0\13\11\1\0\1\11\4\0\1\11"+
    "\1\210\21\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\7\11\1\211\13\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\2\11\1\212\20\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\7\11\1\213\13\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\12\11"+
    "\1\214\10\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\7\11\1\215\13\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\10\11\1\216\12\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\13\11\1\217\7\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\1\11"+
    "\1\220\4\11\1\221\14\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\4\11\1\222\16\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\2\11\1\223\20\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\17\11"+
    "\1\224\3\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\1\11\1\225\21\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\2\11\1\226\20\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\5\11\1\227\15\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\10\11"+
    "\1\230\12\11\24\0\6\11\63\0\1\231\1\232\102\0"+
    "\1\233\30\0\1\153\4\0\3\153\56\0\3\153\1\0"+
    "\1\153\11\0\1\234\4\0\3\234\56\0\3\234\1\0"+
    "\1\234\11\0\1\235\4\0\3\235\5\0\1\236\50\0"+
    "\3\235\1\0\1\235\11\0\1\237\4\0\3\237\5\0"+
    "\1\236\50\0\3\237\1\0\1\237\26\0\1\240\103\0"+
    "\1\241\103\0\1\242\103\0\1\243\103\0\1\244\103\0"+
    "\1\245\103\0\1\246\103\0\1\247\56\0\4\71\1\6"+
    "\1\177\76\71\10\0\1\201\1\202\1\250\1\0\5\202"+
    "\1\0\1\202\4\0\1\202\1\0\1\250\2\202\6\0"+
    "\1\202\2\0\1\202\1\0\1\202\26\0\6\202\10\0"+
    "\2\251\1\250\1\0\5\251\1\0\1\251\4\0\1\251"+
    "\1\0\1\250\2\251\6\0\1\251\2\0\1\251\1\0"+
    "\1\251\26\0\6\251\10\0\1\252\1\75\1\200\2\0"+
    "\3\252\1\103\1\104\1\105\6\0\1\200\1\105\12\0"+
    "\1\106\1\0\1\103\26\0\3\252\1\75\1\252\1\106"+
    "\10\0\1\253\1\75\1\200\2\0\3\253\1\103\1\104"+
    "\1\105\6\0\1\200\1\105\12\0\1\106\1\0\1\103"+
    "\26\0\3\253\1\75\1\253\1\106\10\0\2\205\3\0"+
    "\3\205\1\103\24\0\1\106\1\0\1\103\26\0\5\205"+
    "\1\106\10\0\2\205\3\0\3\205\56\0\5\205\100\0"+
    "\1\254\12\0\13\11\1\0\1\11\4\0\2\11\1\255"+
    "\20\11\24\0\6\11\6\0\13\11\1\0\1\11\4\0"+
    "\10\11\1\256\12\11\24\0\6\11\6\0\13\11\1\0"+
    "\1\11\4\0\2\11\1\257\20\11\24\0\6\11\6\0"+
    "\13\11\1\0\1\11\4\0\3\11\1\260\17\11\24\0"+
    "\6\11\6\0\13\11\1\0\1\11\4\0\1\11\1\261"+
    "\21\11\24\0\6\11\6\0\13\11\1\0\1\11\4\0"+
    "\1\11\1\262\21\11\24\0\6\11\6\0\13\11\1\0"+
    "\1\11\4\0\13\11\1\263\7\11\24\0\6\11\6\0"+
    "\13\11\1\0\1\11\4\0\7\11\1\264\13\11\24\0"+
    "\6\11\6\0\13\11\1\0\1\11\4\0\21\11\1\265"+
    "\1\11\24\0\6\11\6\0\13\11\1\0\1\11\4\0"+
    "\10\11\1\266\12\11\24\0\6\11\6\0\13\11\1\0"+
    "\1\11\4\0\7\11\1\267\13\11\24\0\6\11\6\0"+
    "\13\11\1\0\1\11\4\0\1\270\22\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\4\11\1\271\16\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\15\11"+
    "\1\272\5\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\13\11\1\273\7\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\1\11\1\274\21\11\24\0\6\11"+
    "\63\0\1\275\45\0\1\236\66\0\2\276\1\250\1\0"+
    "\5\276\1\0\1\276\4\0\1\276\1\0\1\250\2\276"+
    "\6\0\1\276\2\0\1\276\1\0\1\276\26\0\6\276"+
    "\10\0\1\277\1\75\1\200\2\0\3\277\1\103\1\104"+
    "\1\105\6\0\1\200\1\105\12\0\1\106\1\0\1\103"+
    "\26\0\3\277\1\75\1\277\1\106\10\0\1\300\1\75"+
    "\1\200\2\0\3\300\1\103\1\104\1\105\6\0\1\200"+
    "\1\105\12\0\1\106\1\0\1\103\26\0\3\300\1\75"+
    "\1\300\1\106\100\0\1\301\11\0\13\11\1\0\1\11"+
    "\4\0\3\11\1\302\17\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\6\11\1\303\14\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\10\11\1\304\12\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\10\11"+
    "\1\305\12\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\10\11\1\306\12\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\14\11\1\307\6\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\3\11\1\310\17\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\4\11"+
    "\1\311\16\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\4\11\1\312\16\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\2\11\1\313\20\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\7\11\1\314\13\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\1\11"+
    "\1\315\21\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\14\11\1\316\6\11\24\0\6\11\10\0\2\317"+
    "\1\250\1\0\5\317\1\0\1\317\4\0\1\317\1\0"+
    "\1\250\2\317\6\0\1\317\2\0\1\317\1\0\1\317"+
    "\26\0\6\317\10\0\1\320\1\75\1\200\2\0\3\320"+
    "\1\103\1\104\1\105\6\0\1\200\1\105\12\0\1\106"+
    "\1\0\1\103\26\0\3\320\1\75\1\320\1\106\10\0"+
    "\1\321\1\75\1\200\2\0\3\321\1\103\1\104\1\105"+
    "\6\0\1\200\1\105\12\0\1\106\1\0\1\103\26\0"+
    "\3\321\1\75\1\321\1\106\77\0\1\322\12\0\13\11"+
    "\1\0\1\11\4\0\4\11\1\323\16\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\11\11\1\324\11\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\1\11"+
    "\1\325\6\11\1\326\12\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\7\11\1\327\13\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\5\11\1\330\15\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\3\11"+
    "\1\331\17\11\24\0\6\11\6\0\13\11\1\0\1\11"+
    "\4\0\13\11\1\332\7\11\24\0\6\11\6\0\13\11"+
    "\1\0\1\11\4\0\7\11\1\333\13\11\24\0\6\11"+
    "\6\0\13\11\1\0\1\11\4\0\3\11\1\334\17\11"+
    "\24\0\6\11\6\0\13\11\1\0\1\11\4\0\22\11"+
    "\1\335\24\0\6\11\10\0\2\336\1\250\1\0\5\336"+
    "\1\0\1\336\4\0\1\336\1\0\1\250\2\336\6\0"+
    "\1\336\2\0\1\336\1\0\1\336\26\0\6\336\10\0"+
    "\1\337\1\75\1\200\2\0\3\337\1\103\1\104\1\105"+
    "\6\0\1\200\1\105\12\0\1\106\1\0\1\103\26\0"+
    "\3\337\1\75\1\337\1\106\10\0\1\340\1\75\1\200"+
    "\2\0\3\340\1\103\1\104\1\105\6\0\1\200\1\105"+
    "\12\0\1\106\1\0\1\103\26\0\3\340\1\75\1\340"+
    "\1\106\101\0\1\341\10\0\13\11\1\0\1\11\4\0"+
    "\5\11\1\342\15\11\24\0\6\11\6\0\13\11\1\0"+
    "\1\11\4\0\3\11\1\343\17\11\24\0\6\11\6\0"+
    "\13\11\1\0\1\11\4\0\1\11\1\344\21\11\24\0"+
    "\6\11\6\0\13\11\1\0\1\11\4\0\4\11\1\345"+
    "\16\11\24\0\6\11\6\0\13\11\1\0\1\11\4\0"+
    "\4\11\1\346\16\11\24\0\6\11\6\0\13\11\1\0"+
    "\1\11\4\0\7\11\1\347\13\11\24\0\6\11\6\0"+
    "\13\11\1\0\1\11\4\0\7\11\1\350\13\11\24\0"+
    "\6\11\6\0\13\11\1\0\1\11\4\0\3\11\1\351"+
    "\17\11\24\0\6\11\10\0\2\352\1\250\1\0\5\352"+
    "\1\0\1\352\4\0\1\352\1\0\1\250\2\352\6\0"+
    "\1\352\2\0\1\352\1\0\1\352\26\0\6\352\10\0"+
    "\1\353\1\75\1\200\2\0\3\353\1\103\1\104\1\105"+
    "\6\0\1\200\1\105\12\0\1\106\1\0\1\103\26\0"+
    "\3\353\1\75\1\353\1\106\10\0\1\354\1\75\1\200"+
    "\2\0\3\354\1\103\1\104\1\105\6\0\1\200\1\105"+
    "\12\0\1\106\1\0\1\103\26\0\3\354\1\75\1\354"+
    "\1\106\15\0\1\355\74\0\13\11\1\0\1\11\4\0"+
    "\1\11\1\356\21\11\24\0\6\11\6\0\13\11\1\0"+
    "\1\11\4\0\5\11\1\357\15\11\24\0\6\11\6\0"+
    "\13\11\1\0\1\11\4\0\11\11\1\360\11\11\24\0"+
    "\6\11\6\0\13\11\1\0\1\11\4\0\7\11\1\361"+
    "\13\11\24\0\6\11\6\0\13\11\1\0\1\11\4\0"+
    "\3\11\1\362\17\11\24\0\6\11\10\0\2\363\1\250"+
    "\1\0\5\363\1\0\1\363\4\0\1\363\1\0\1\250"+
    "\2\363\6\0\1\363\2\0\1\363\1\0\1\363\26\0"+
    "\6\363\10\0\1\364\1\75\1\200\2\0\3\364\1\103"+
    "\1\104\1\105\6\0\1\200\1\105\12\0\1\106\1\0"+
    "\1\103\26\0\3\364\1\75\1\364\1\106\10\0\1\365"+
    "\1\75\1\200\2\0\3\365\1\103\1\104\1\105\6\0"+
    "\1\200\1\105\12\0\1\106\1\0\1\103\26\0\3\365"+
    "\1\75\1\365\1\106\102\0\1\366\7\0\13\11\1\0"+
    "\1\11\4\0\7\11\1\367\13\11\24\0\6\11\6\0"+
    "\13\11\1\0\1\11\4\0\12\11\1\370\10\11\24\0"+
    "\6\11\6\0\13\11\1\0\1\11\4\0\1\11\1\371"+
    "\21\11\24\0\6\11\6\0\13\11\1\0\1\11\4\0"+
    "\16\11\1\372\4\11\24\0\6\11\10\0\2\373\1\250"+
    "\1\0\5\373\1\0\1\373\4\0\1\373\1\0\1\250"+
    "\2\373\6\0\1\373\2\0\1\373\1\0\1\373\26\0"+
    "\6\373\10\0\1\374\1\75\1\200\2\0\3\374\1\103"+
    "\1\104\1\105\6\0\1\200\1\105\12\0\1\106\1\0"+
    "\1\103\26\0\3\374\1\75\1\374\1\106\10\0\1\375"+
    "\1\75\1\200\2\0\3\375\1\103\1\104\1\105\6\0"+
    "\1\200\1\105\12\0\1\106\1\0\1\103\26\0\3\375"+
    "\1\75\1\375\1\106\77\0\1\376\12\0\13\11\1\0"+
    "\1\11\4\0\6\11\1\377\14\11\24\0\6\11\6\0"+
    "\13\11\1\0\1\11\4\0\6\11\1\u0100\14\11\24\0"+
    "\6\11\10\0\2\u0101\1\250\1\0\5\u0101\1\0\1\u0101"+
    "\4\0\1\u0101\1\0\1\250\2\u0101\6\0\1\u0101\2\0"+
    "\1\u0101\1\0\1\u0101\26\0\6\u0101\10\0\1\u0102\1\75"+
    "\1\200\2\0\3\u0102\1\103\1\104\1\105\6\0\1\200"+
    "\1\105\12\0\1\106\1\0\1\103\26\0\3\u0102\1\75"+
    "\1\u0102\1\106\10\0\1\u0103\1\75\1\200\2\0\3\u0103"+
    "\1\103\1\104\1\105\6\0\1\200\1\105\12\0\1\106"+
    "\1\0\1\103\26\0\3\u0103\1\75\1\u0103\1\106\101\0"+
    "\1\u0104\12\0\2\u0105\1\250\1\0\5\u0105\1\0\1\u0105"+
    "\4\0\1\u0105\1\0\1\250\2\u0105\6\0\1\u0105\2\0"+
    "\1\u0105\1\0\1\u0105\26\0\6\u0105\10\0\1\u0106\1\75"+
    "\1\200\2\0\3\u0106\1\103\1\104\1\105\6\0\1\200"+
    "\1\105\12\0\1\106\1\0\1\103\26\0\3\u0106\1\75"+
    "\1\u0106\1\106\10\0\1\u0107\1\75\1\200\2\0\3\u0107"+
    "\1\103\1\104\1\105\6\0\1\200\1\105\12\0\1\106"+
    "\1\0\1\103\26\0\3\u0107\1\75\1\u0107\1\106\10\0"+
    "\2\u0108\1\250\1\0\5\u0108\1\0\1\u0108\4\0\1\u0108"+
    "\1\0\1\250\2\u0108\6\0\1\u0108\2\0\1\u0108\1\0"+
    "\1\u0108\26\0\6\u0108\10\0\1\u0109\1\75\1\200\2\0"+
    "\3\u0109\1\103\1\104\1\105\6\0\1\200\1\105\12\0"+
    "\1\106\1\0\1\103\26\0\3\u0109\1\75\1\u0109\1\106"+
    "\10\0\1\u010a\1\75\1\200\2\0\3\u010a\1\103\1\104"+
    "\1\105\6\0\1\200\1\105\12\0\1\106\1\0\1\103"+
    "\26\0\3\u010a\1\75\1\u010a\1\106\10\0\2\u010b\1\250"+
    "\1\0\5\u010b\1\0\1\u010b\4\0\1\u010b\1\0\1\250"+
    "\2\u010b\6\0\1\u010b\2\0\1\u010b\1\0\1\u010b\26\0"+
    "\6\u010b\10\0\1\u010c\1\75\1\200\2\0\3\u010c\1\103"+
    "\1\104\1\105\6\0\1\200\1\105\12\0\1\106\1\0"+
    "\1\103\26\0\3\u010c\1\75\1\u010c\1\106\10\0\1\u010d"+
    "\1\75\1\200\2\0\3\u010d\1\103\1\104\1\105\6\0"+
    "\1\200\1\105\12\0\1\106\1\0\1\103\26\0\3\u010d"+
    "\1\75\1\u010d\1\106\10\0\2\u010e\1\250\1\0\5\u010e"+
    "\1\0\1\u010e\4\0\1\u010e\1\0\1\250\2\u010e\6\0"+
    "\1\u010e\2\0\1\u010e\1\0\1\u010e\26\0\6\u010e\10\0"+
    "\1\u010f\1\75\1\200\2\0\3\u010f\1\103\1\104\1\105"+
    "\6\0\1\200\1\105\12\0\1\106\1\0\1\103\26\0"+
    "\3\u010f\1\75\1\u010f\1\106\10\0\1\u0110\1\75\1\200"+
    "\2\0\3\u0110\1\103\1\104\1\105\6\0\1\200\1\105"+
    "\12\0\1\106\1\0\1\103\26\0\3\u0110\1\75\1\u0110"+
    "\1\106\10\0\2\u0111\1\250\1\0\5\u0111\1\0\1\u0111"+
    "\4\0\1\u0111\1\0\1\250\2\u0111\6\0\1\u0111\2\0"+
    "\1\u0111\1\0\1\u0111\26\0\6\u0111\10\0\1\u0112\1\75"+
    "\1\200\2\0\3\u0112\1\103\1\104\1\105\6\0\1\200"+
    "\1\105\12\0\1\106\1\0\1\103\26\0\3\u0112\1\75"+
    "\1\u0112\1\106\10\0\1\u0113\1\75\1\200\2\0\3\u0113"+
    "\1\103\1\104\1\105\6\0\1\200\1\105\12\0\1\106"+
    "\1\0\1\103\26\0\3\u0113\1\75\1\u0113\1\106\10\0"+
    "\2\u0114\1\250\1\0\5\u0114\1\0\1\u0114\4\0\1\u0114"+
    "\1\0\1\250\2\u0114\6\0\1\u0114\2\0\1\u0114\1\0"+
    "\1\u0114\26\0\6\u0114\10\0\1\u0115\1\75\1\200\2\0"+
    "\3\u0115\1\103\1\104\1\105\6\0\1\200\1\105\12\0"+
    "\1\106\1\0\1\103\26\0\3\u0115\1\75\1\u0115\1\106"+
    "\10\0\1\u0116\1\75\1\200\2\0\3\u0116\1\103\1\104"+
    "\1\105\6\0\1\200\1\105\12\0\1\106\1\0\1\103"+
    "\26\0\3\u0116\1\75\1\u0116\1\106\10\0\2\u0117\1\250"+
    "\1\0\5\u0117\1\0\1\u0117\4\0\1\u0117\1\0\1\250"+
    "\2\u0117\6\0\1\u0117\2\0\1\u0117\1\0\1\u0117\26\0"+
    "\6\u0117\10\0\1\u0118\1\75\1\200\2\0\3\u0118\1\103"+
    "\1\104\1\105\6\0\1\200\1\105\12\0\1\106\1\0"+
    "\1\103\26\0\3\u0118\1\75\1\u0118\1\106\12\0\1\250"+
    "\16\0\1\250\62\0\1\u0119\1\75\1\200\2\0\3\u0119"+
    "\1\103\1\104\1\105\6\0\1\200\1\105\12\0\1\106"+
    "\1\0\1\103\26\0\3\u0119\1\75\1\u0119\1\106\10\0"+
    "\1\u011a\1\75\1\200\2\0\3\u011a\1\103\1\104\1\105"+
    "\6\0\1\200\1\105\12\0\1\106\1\0\1\103\26\0"+
    "\3\u011a\1\75\1\u011a\1\106\10\0\1\u011b\1\75\1\200"+
    "\2\0\3\u011b\1\103\1\104\1\105\6\0\1\200\1\105"+
    "\12\0\1\106\1\0\1\103\26\0\3\u011b\1\75\1\u011b"+
    "\1\106\10\0\1\u011c\1\75\1\200\2\0\3\u011c\1\103"+
    "\1\104\1\105\6\0\1\200\1\105\12\0\1\106\1\0"+
    "\1\103\26\0\3\u011c\1\75\1\u011c\1\106\10\0\2\75"+
    "\1\200\2\0\3\75\1\103\1\104\1\105\6\0\1\200"+
    "\1\105\12\0\1\106\1\0\1\103\26\0\5\75\1\106";

  private static int [] zzUnpackTrans() {
    int [] result = new int[13668];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\7\1\2\11\13\1\11\11"+
    "\4\1\2\11\7\1\2\11\3\1\1\11\2\1\1\0"+
    "\2\11\2\1\1\11\1\0\3\1\1\11\1\1\1\0"+
    "\3\11\1\0\21\1\2\11\1\1\1\11\1\1\12\11"+
    "\2\1\11\11\12\1\1\0\1\11\5\1\2\0\21\1"+
    "\1\11\1\1\2\11\1\0\1\11\1\0\11\11\3\1"+
    "\1\0\20\1\1\11\3\1\1\0\20\1\1\0\16\1"+
    "\1\0\13\1\1\0\10\1\1\0\7\1\1\0\2\1"+
    "\1\0\2\1\1\11\1\0\2\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\1\0\2\1\1\0\2\1\1\0"+
    "\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
    return new JavaSymbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new JavaSymbol(type, yyline+1, yycolumn+1, value);
  }

  /** 
   * assumes correct representation of a long value for 
   * specified radix in scanner buffer from <code>start</code> 
   * to <code>end</code> 
   */
  private long parseLong(int start, int end, int radix) {
    long result = 0;
    long digit;

    for (int i = start; i < end; i++) {
      digit  = Character.digit(yycharat(i),radix);
      result*= radix;
      result+= digit;
    }

    return result;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1792) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 47: 
          { return symbol(GTEQ);
          }
        case 106: break;
        case 29: 
          { return symbol(XOR);
          }
        case 107: break;
        case 21: 
          { return symbol(GT);
          }
        case 108: break;
        case 51: 
          { return symbol(NOTEQ);
          }
        case 109: break;
        case 9: 
          { yybegin(STRING); string.setLength(0);
          }
        case 110: break;
        case 14: 
          { return symbol(LBRACE);
          }
        case 111: break;
        case 20: 
          { return symbol(EQ);
          }
        case 112: break;
        case 42: 
          { return symbol(MINUSMINUS);
          }
        case 113: break;
        case 91: 
          { return symbol(CONTINUE);
          }
        case 114: break;
        case 41: 
          { return symbol(FLOATING_POINT_LITERAL, new Double(yytext().substring(0,yylength()-1)));
          }
        case 115: break;
        case 45: 
          { return symbol(DO);
          }
        case 116: break;
        case 57: 
          { return symbol(PLUSPLUS);
          }
        case 117: break;
        case 22: 
          { return symbol(LT);
          }
        case 118: break;
        case 52: 
          { return symbol(ANDEQ);
          }
        case 119: break;
        case 67: 
          { string.append( '\t' );
          }
        case 120: break;
        case 59: 
          { return symbol(MODEQ);
          }
        case 121: break;
        case 83: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\t'));
          }
        case 122: break;
        case 100: 
          { return symbol(BOOLEAN);
          }
        case 123: break;
        case 10: 
          { yybegin(CHARLITERAL);
          }
        case 124: break;
        case 46: 
          { return symbol(EQEQ);
          }
        case 125: break;
        case 40: 
          { return symbol(FLOATING_POINT_LITERAL, new Float(yytext().substring(0,yylength()-1)));
          }
        case 126: break;
        case 89: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(true));
          }
        case 127: break;
        case 27: 
          { return symbol(OR);
          }
        case 128: break;
        case 28: 
          { return symbol(PLUS);
          }
        case 129: break;
        case 66: 
          { string.append( '\n' );
          }
        case 130: break;
        case 13: 
          { return symbol(RPAREN);
          }
        case 131: break;
        case 82: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\n'));
          }
        case 132: break;
        case 48: 
          { return symbol(RSHIFT);
          }
        case 133: break;
        case 36: 
          { return symbol(MULTEQ);
          }
        case 134: break;
        case 99: 
          { return symbol(PRIVATE);
          }
        case 135: break;
        case 75: 
          { return symbol(URSHIFT);
          }
        case 136: break;
        case 90: 
          { return symbol(URSHIFTEQ);
          }
        case 137: break;
        case 72: 
          { return symbol(INTEGER_LITERAL, new Integer((int) parseLong(2, yylength(), 16)));
          }
        case 138: break;
        case 73: 
          { return symbol(FOR);
          }
        case 139: break;
        case 86: 
          { return symbol(INTEGER_LITERAL, new Long(parseLong(2, yylength()-1, 16)));
          }
        case 140: break;
        case 38: 
          { return symbol(FLOATING_POINT_LITERAL, new Double(yytext()));
          }
        case 141: break;
        case 35: 
          { return symbol(DIVEQ);
          }
        case 142: break;
        case 25: 
          { return symbol(QUESTION);
          }
        case 143: break;
        case 3: 
          { return symbol(DIV);
          }
        case 144: break;
        case 95: 
          { return symbol(DOUBLE);
          }
        case 145: break;
        case 88: 
          { return symbol(CHAR);
          }
        case 146: break;
        case 44: 
          { return symbol(IF);
          }
        case 147: break;
        case 5: 
          { return symbol(IDENTIFIER, yytext());
          }
        case 148: break;
        case 60: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 149: break;
        case 101: 
          { return symbol(PACKAGE);
          }
        case 150: break;
        case 58: 
          { return symbol(XOREQ);
          }
        case 151: break;
        case 76: 
          { return symbol(LSHIFTEQ);
          }
        case 152: break;
        case 30: 
          { return symbol(MOD);
          }
        case 153: break;
        case 12: 
          { return symbol(LPAREN);
          }
        case 154: break;
        case 68: 
          { string.append( '\r' );
          }
        case 155: break;
        case 50: 
          { return symbol(LSHIFT);
          }
        case 156: break;
        case 104: 
          { return symbol(BREAK);
          }
        case 157: break;
        case 87: 
          { return symbol(NULL_LITERAL);
          }
        case 158: break;
        case 24: 
          { return symbol(COMP);
          }
        case 159: break;
        case 65: 
          { string.append( '\b' );
          }
        case 160: break;
        case 84: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\r'));
          }
        case 161: break;
        case 43: 
          { return symbol(MINUSEQ);
          }
        case 162: break;
        case 81: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\b'));
          }
        case 163: break;
        case 39: 
          { return symbol(INTEGER_LITERAL, new Long(yytext().substring(0,yylength()-1)));
          }
        case 164: break;
        case 32: 
          { throw new RuntimeException("Unterminated string at end of line");
          }
        case 165: break;
        case 62: 
          { string.append( '\"' );
          }
        case 166: break;
        case 1: 
          { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+yyline+", column "+yycolumn);
          }
        case 167: break;
        case 54: 
          { return symbol(OREQ);
          }
        case 168: break;
        case 37: 
          { return symbol(INTEGER_LITERAL, new Integer((int) parseLong(0, yylength(), 8)));
          }
        case 169: break;
        case 17: 
          { return symbol(RBRACK);
          }
        case 170: break;
        case 18: 
          { return symbol(SEMICOLON);
          }
        case 171: break;
        case 6: 
          { return symbol(INTEGER_LITERAL, new Integer(yytext()));
          }
        case 172: break;
        case 78: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\"'));
          }
        case 173: break;
        case 97: 
          { return symbol(IMPORT);
          }
        case 174: break;
        case 63: 
          { string.append( '\'' );
          }
        case 175: break;
        case 92: 
          { return symbol(FLOAT);
          }
        case 176: break;
        case 64: 
          { string.append( '\\' );
          }
        case 177: break;
        case 8: 
          { return symbol(MINUS);
          }
        case 178: break;
        case 79: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\''));
          }
        case 179: break;
        case 7: 
          { return symbol(DOT);
          }
        case 180: break;
        case 80: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\\'));
          }
        case 181: break;
        case 94: 
          { return symbol(INT);
          }
        case 182: break;
        case 74: 
          { return symbol(RSHIFTEQ);
          }
        case 183: break;
        case 102: 
          { return symbol(PROTECTED);
          }
        case 184: break;
        case 26: 
          { return symbol(AND);
          }
        case 185: break;
        case 105: 
          { return symbol(INTEGER_LITERAL, new Integer(Integer.MIN_VALUE));
          }
        case 186: break;
        case 11: 
          { return symbol(COLON);
          }
        case 187: break;
        case 49: 
          { return symbol(LTEQ);
          }
        case 188: break;
        case 77: 
          { yybegin(YYINITIAL); 
			                              int val = Integer.parseInt(yytext().substring(1,yylength()-1),8);
			                            return symbol(CHARACTER_LITERAL, new Character((char)val));
          }
        case 189: break;
        case 69: 
          { string.append( '\f' );
          }
        case 190: break;
        case 23: 
          { return symbol(NOT);
          }
        case 191: break;
        case 33: 
          { yybegin(YYINITIAL); return symbol(STRING_LITERAL, string.toString());
          }
        case 192: break;
        case 15: 
          { return symbol(RBRACE);
          }
        case 193: break;
        case 85: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\f'));
          }
        case 194: break;
        case 71: 
          { return symbol(INTEGER_LITERAL, new Long(parseLong(0, yylength()-1, 8)));
          }
        case 195: break;
        case 4: 
          { return symbol(MULT);
          }
        case 196: break;
        case 2: 
          { /* ignore */
          }
        case 197: break;
        case 16: 
          { return symbol(LBRACK);
          }
        case 198: break;
        case 55: 
          { return symbol(OROR);
          }
        case 199: break;
        case 31: 
          { string.append( yytext() );
          }
        case 200: break;
        case 93: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(false));
          }
        case 201: break;
        case 53: 
          { return symbol(ANDAND);
          }
        case 202: break;
        case 61: 
          { char val = (char) Integer.parseInt(yytext().substring(1),8);
                        				   string.append( val );
          }
        case 203: break;
        case 96: 
          { return symbol(WHILE);
          }
        case 204: break;
        case 34: 
          { throw new RuntimeException("Unterminated character literal at end of line");
          }
        case 205: break;
        case 56: 
          { return symbol(PLUSEQ);
          }
        case 206: break;
        case 103: 
          { return symbol(ELSE);
          }
        case 207: break;
        case 70: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character(yytext().charAt(0)));
          }
        case 208: break;
        case 19: 
          { return symbol(COMMA);
          }
        case 209: break;
        case 98: 
          { return symbol(RETURN);
          }
        case 210: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          scanner = new Scanner( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
