package main;

public enum Symbol {
	SE, ALTRIMENTI, FINCHE, INTERO, PARENTESI_QUADRA_APERTA,
	PARENTESI_QUADRA_CHIUSA, DUE_PUNTI, PUNTO, VIRGOLA, PARENTESI_TONDA_APERTA,
	PARENTESI_TONDA_CHIUSA, UGUALE, LEGGI, STAMPA, COMMENTO, IDENTIFICATORE,
	NUMERO_INTERO, SOMMA, SOTTRAZIONE, ASSEGNAZIONE, FINE_FILE
}
