package main;

import edu.tum.cup2.grammar.Terminal;

public enum TipoSimbolo implements Terminal {
	SE, ALTRIMENTI, FINCHE, INTERO, PARENTESI_QUADRA_APERTA,
	PARENTESI_QUADRA_CHIUSA, DUE_PUNTI, PUNTO, VIRGOLA, PARENTESI_TONDA_APERTA,
	PARENTESI_TONDA_CHIUSA, UGUALE, LEGGI, SCRIVI, COMMENTO, IDENTIFICATORE,
	NUMERO_INTERO, SOMMA, SOTTRAZIONE, ASSEGNAZIONE, FINE_FILE, STRINGA
}
